// src/components/footer/footer.tsx
import { Link } from "gatsby";
import React, { useState, useEffect } from "react";
import styles from "./footer.style";
import { Newsletter } from "@components";
import { navigation } from "@utils";
import Youtube from "@svgs/youtube";
import Twitter from "@svgs/twitter";
import Github from "@svgs/github";
import Instagram from "@svgs/instagram";

const Footer = ({ siteUrl }: { siteUrl: string }) => {
    return (
        <footer css={styles}>
            <div className="container">
                <div className="footer-row">
                    <div className="footer-column">
                        <Newsletter />
                    </div>
                    <div className="footer-column links">
                        <div className="quick">
                            <h3>Site Links:</h3>
                            <nav
                                className="navigation"
                                role="navigation"
                                aria-label="Footer Navigation"
                            >
                                <ul>
                                    {navigation.map(item => {
                                        return (
                                            <li key={item.title}>
                                                <Link activeClassName="active" to={item.to}>
                                                    {item.title}
                                                </Link>
                                            </li>
                                        );
                                    })}
                                </ul>
                            </nav>
                        </div>
                        <div className="external">
                            <h3>External Links:</h3>

                            <ul>
                                <li>
                                    <a href="https://medium.com/@alialaa">My Articles on Medium</a>
                                </li>
                                <li>
                                    <a href="https://css-tricks.com/author/alialaa">
                                        My Articles on CSS Tricks
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.udemy.com/user/ali-alaa-3/">
                                        My Courses on Udemy
                                    </a>
                                </li>
                                <li>
                                    <a href="https://alialaa.github.io/css-grid-cheat-sheet/">
                                        CSS Grid Cheat Sheet
                                    </a>
                                </li>
                                <li>
                                    <a href={`${siteUrl}/rss.xml`}>Articles RSS Feed</a>
                                </li>
                            </ul>
                        </div>
                        <div className="social">
                            <h3>Find me on:</h3>

                            <ul>
                                <li>
                                    <a href="https://twitter.com/alialaa">
                                        <Twitter focusable="false" aria-hidden />
                                        <span>
                                            <span className="visually-hidden">Follow me on </span>
                                            Twitter
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.instagram.com/alialaa17/">
                                        <Instagram focusable="false" aria-hidden />
                                        <span>
                                            <span className="visually-hidden">Follow me on </span>
                                            Instagram
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.youtube.com/channel/UCa-VVCGLQZv6IQWTKyVlnjg">
                                        <Youtube focusable="false" aria-hidden />
                                        <span>
                                            <span className="visually-hidden">
                                                Subscribe to my{" "}
                                            </span>
                                            YouTube<span className="visually-hidden"> channel</span>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://github.com/alialaa/">
                                        <Github focusable="false" aria-hidden />
                                        <span>
                                            <span className="visually-hidden">Follow me on </span>
                                            GitHub
                                        </span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div className="logo">
                    <svg aria-hidden focusable="false" viewBox="0 0 434 219.675">
                        <path
                            fill="#090909"
                            stroke="#090909"
                            strokeWidth="3"
                            d="M432.5,146.5h-40.881l-53.456-145h-1h-29h-1
l-53.456,145h-70.088l-53.456-145h-1h-29h-1l-53.456,145H1.5v31h32.778l-15.115,40.25l36.083,0.413L69.223,177.5h90.88
l13.976,40.288l36.084,0.337L195.048,177.5h47.23l-15.115,40.25l36.084,0.413l13.976-40.663h90.879l13.977,40.288l36.084,0.337
L403.048,177.5H432.5V146.5z M79.78,146.5l34.883-102.424L149.545,146.5H79.78z M287.781,146.5l34.882-102.424L357.545,146.5
H287.781z"
                        />
                    </svg>
                </div>
                <div className="copyright">
                    Copyright &copy; 2020 Ali Alaa. All Rights Reserved.
                </div>
            </div>
        </footer>
    );
};
export default Footer;

// src/lib/components/Footer.svelte
<script>
	import { page } from '$app/stores';

	import { navigationItems } from '$lib/utils/navigation';
	import Logo from './Logo.svelte';
	import Newsletter from './Newsletter.svelte';
	import SocialIcon from './SocialIcon.svelte';
	import Waves from './Waves.svelte';
	import ZigLine from './ZigLine.svelte';

	let { colorScheme } = $props();
</script>

<footer class="footer">
	<div style="text-align: center;">
		<ZigLine height="30px" color={colorScheme === 'dark' ? '#262233' : '#e3ddf5'} />
	</div>
	<div class="content-wrapper">
		<div class="footer-row">
			<div class="footer-column"><Newsletter /></div>
			<div class="footer-column links">
				<div class="quick">
					<h3>Site Links:</h3>
					<nav class="navigation" role="navigation" aria-label="Footer Navigation">
						<ul>
							{#each navigationItems as navigationItem}
								{@const isCurrent = $page.url.pathname === navigationItem.path}
								<li class:active={isCurrent}>
									<a href={navigationItem.path}
										>{navigationItem.title}{#if isCurrent}<span class="visually-hidden">
												(current page)</span
											>{/if}</a
									>
								</li>
							{/each}
						</ul>
					</nav>
				</div>
				<div class="external">
					<h3>External Links:</h3>

					<ul>
						<li>
							<a href="https://medium.com/@alialaa">My Articles on Medium</a>
						</li>
						<li>
							<a href="https://css-tricks.com/author/alialaa"> My Articles on CSS Tricks </a>
						</li>
						<li>
							<a href="https://www.udemy.com/user/ali-alaa-3/"> My Courses on Udemy </a>
						</li>
						<li>
							<a href="https://alialaa.github.io/css-grid-cheat-sheet/"> CSS Grid Cheat Sheet </a>
						</li>
						<li>
							<a href={`${$page.url.origin}/rss.xml`}>Articles RSS Feed</a>
						</li>
					</ul>
				</div>
				<div class="social">
					<h3>Find me on:</h3>

					<ul>
						<li>
							<a href="https://x.com/alialaa">
								<SocialIcon class="x" platform="X" focusable="false" aria-hidden="true" />
								<span>
									<span class="visually-hidden">Follow me on </span>X
								</span>
							</a>
						</li>
						<li>
							<a href="https://www.instagram.com/alialaa17/">
								<SocialIcon platform="Instagram" focusable="false" aria-hidden="true" />
								<span>
									<span class="visually-hidden">Follow me on </span>Instagram
								</span>
							</a>
						</li>
						<li>
							<a href="https://www.youtube.com/channel/UCa-VVCGLQZv6IQWTKyVlnjg">
								<SocialIcon platform="Youtube" focusable="false" aria-hidden="true" />
								<span>
									<span class="visually-hidden">
										Subscribe to my{' '}
									</span>YouTube<span class="visually-hidden"> channel</span>
								</span>
							</a>
						</li>
						<li>
							<a href="https://github.com/alialaa/">
								<SocialIcon platform="Github" focusable="false" aria-hidden="true" />
								<span><span class="visually-hidden">Follow me on </span>GitHub</span>
							</a>
						</li>
						<li>
							<a href="https://bsky.app/profile/alialaa.bsky.social">
								<SocialIcon class="bsky" platform="Bluesky" focusable="false" aria-hidden="true" />
								<span>
									<span class="visually-hidden">Follow me on </span>Bluesky
								</span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="logo">
			<Logo animate={false} />
		</div>
		<div class="copyright">Copyright &copy; 2020 Ali Alaa. All Rights Reserved.</div>
	</div>
</footer>

<style lang="scss">
	.footer {
		padding: functions.toRem(80) 0;
		background-color: var(--card);
		position: relative;
		z-index: 22;
		:global(.zigzag-line) {
			position: absolute;
			top: -14px;
			left: 0;
			// margin-bottom: functions.toRem(40);
		}
		.footer-row {
			display: grid;
			grid-template-columns: 1fr;
			gap: 60px;
			@include breakpoint.up('lg') {
				grid-template-columns: 1fr 1.2fr;
				gap: 80px;
			}
			.links {
				display: grid;
				grid-template-columns: 1fr;
				gap: 50px;
				align-content: flex-start;
				@include breakpoint.up('md') {
					grid-template-columns: 1fr 1fr;
					gap: 30px;
				}
				h3 {
					font-weight: 800;
					font-size: functions.toRem(24);
					@include breakpoint.down('sm') {
						font-size: functions.toRem(28);
					}
				}
				ul {
					padding: 0;
					margin: 0;
					list-style: none;
					li {
						/* display: inline-block; */
						/* margin-right: 2rem; */
						margin-bottom: 3px;
						@include breakpoint.down('sm') {
							margin-bottom: 0;
						}
						a {
							font-weight: 500;
							font-size: functions.toRem(16);
							text-decoration: underline var(--purple);
							@include breakpoint.down('sm') {
								min-height: 48px;
								display: inline-flex;
								align-items: center;
							}
						}
					}
				}
				.social {
					@include breakpoint.up('sm') {
						grid-area: auto / span 2 / auto / auto;
					}
					h3 {
						margin-bottom: functions.toRem(5);
					}
					ul {
						/* display: flex; */
						margin: 0 -15px;
						li {
							display: inline-block;
							margin: 15px;
							a {
								text-decoration: none;
								span {
									text-decoration: underline var(--purple);
								}
								:global(svg) {
									width: 25px;
									height: auto;
									vertical-align: middle;
									margin-right: 10px;
								}
								:global(svg.x),
								:global(svg.bsky) {
									width: 22px;
									height: auto;
									vertical-align: middle;
								}
								:global(svg path) {
									fill: var(--text);
								}
							}
						}
					}
				}
			}
		}
		.logo {
			text-align: center;
			padding: functions.toRem(60) 0 functions.toRem(10);
			@include breakpoint.up('sm') {
				padding: functions.toRem(80) 0 functions.toRem(10);
			}
			:global(svg) {
				width: 60px;
			}
		}
		.copyright {
			text-align: center;
			font-weight: 600;
		}
	}
</style>
